### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by griffhurt** [2m/polyfact#1]
Would it be possible to add a license to this repository so that it could be used in other projects? [Choose a license](https://choosealicense.com/) is great for helping with this. Thanks.

**Comment by 2m** [comment]
Sure! I usually go with Apache 2. Does that work for you?

**Comment by griffhurt** [comment]
Yep, that works great, thanks!

**Comment by 2m** [comment]
@griffhurt added license and also released version `1.0` to Maven Central, if you would like to depend on it as a library dependency. Let me know if you need anyhing else. Also, feel free to create PRs if you see that something can be improved. :)
